import React from 'react';

const Edu2024 = ({cx}) => {
    return (
        <>
            <div className={cx("tb_style_1")}>
                <table>
                    <colgroup>
                        <col style={{width:"5%"}} />
                        <col style={{width:"30%"}} />
                        <col />
                        <col />
                        <col />
                        <col />
                        <col />
                        <col />
                    </colgroup>
                    <thead>
                        <tr>
                            <th scope="col">학수번호</th>
                            <th scope="col">교과목명</th>
                            <th scope="col">단위</th>
                            <th scope="col" colSpan="3">학-강-실</th>
                            <th scope="col">관장학과</th>
                            <th scope="col">비고</th>
                        </tr>
                    </thead>
                    <tbody>
                        <tr>
                            <td>CUL1156</td>
                            <td>4차산업혁명과창업</td>
                            <td>100</td>
                            <td>3</td>
                            <td>3</td>
                            <td>0</td>
                            <td>파이낸스경영학과</td>
                            <td></td>
                        </tr>
                        <tr>
                            <td>GEN5010</td>
                            <td>지적재산법</td>
                            <td>100</td>
                            <td>2</td>
                            <td>2</td>
                            <td>0</td>
                            <td>법학전문대학원</td>
                            <td></td>
                        </tr>
                        <tr>
                            <td>GEN6006</td>
                            <td>특허법의이해</td>
                            <td>100</td>
                            <td>2</td>
                            <td>2</td>
                            <td>0</td>
                            <td>창의융합교육팀</td>
                            <td></td>
                        </tr>
                        <tr>
                            <td>CUL0135</td>
                            <td>글로벌기업가정신</td>
                            <td>200</td>
                            <td>3</td>
                            <td>3</td>
                            <td>0</td>
                            <td>글로벌기업가센터</td>
                            <td></td>
                        </tr>
                        <tr>
                            <td>VEN2015</td>
                            <td>레드라이언을위한씽씽스타트업1</td>
                            <td>200</td>
                            <td>3</td>
                            <td>2</td>
                            <td>1</td>
                            <td>국제팀(행정부서대학)</td>
                            <td>레드라이언전용강좌</td>
                        </tr>
                        <tr>
                            <td>VEN2021</td>
                            <td>세상을바꾸는스타트업이야기</td>
                            <td>200</td>
                            <td>2</td>
                            <td>2</td>
                            <td>0</td>
                            <td>글로벌기업가센터</td>
                            <td></td>
                        </tr>
                        <tr>
                            <td>VEN6001</td>
                            <td>스타트업토크콘서트</td>
                            <td>200</td>
                            <td>2</td>
                            <td>2</td>
                            <td>0</td>
                            <td>글로벌기업가센터</td>
                            <td></td>
                        </tr>
                        <tr>
                            <td>VEN3008</td>
                            <td>창업기초:글로벌스타트업멘토링</td>
                            <td>200</td>
                            <td>3</td>
                            <td>1</td>
                            <td>2</td>
                            <td>글로벌기업가센터</td>
                            <td></td>
                        </tr>
                        <tr>
                            <td>VEN2005</td>
                            <td>창업기초:디자인씽킹</td>
                            <td>200</td>
                            <td>3</td>
                            <td>0</td>
                            <td>3</td>
                            <td>글로벌기업가센터</td>
                            <td></td>
                        </tr>
                        <tr>
                            <td>VEN3011</td>
                            <td>창업기초:문화예술산업의이해</td>
                            <td>200</td>
                            <td>3</td>
                            <td>2</td>
                            <td>1</td>
                            <td>글로벌기업가센터</td>
                            <td></td>
                        </tr>
                        <tr>
                            <td>VEN2005</td>
                            <td>창업기초:디자인씽킹</td>
                            <td>200</td>
                            <td>3</td>
                            <td>0</td>
                            <td>3</td>
                            <td>글로벌기업가센터</td>
                            <td></td>
                        </tr>
                        <tr>
                            <td>VEN2017</td>
                            <td>창업기초:사업기회의발견</td>
                            <td>200</td>
                            <td>3</td>
                            <td>2</td>
                            <td>1</td>
                            <td>글로벌기업가센터</td>
                            <td></td>
                        </tr>
                        <tr>
                            <td>VEN2014</td>
                            <td>창업기초:사회적기업가정신액션러닝</td>
                            <td>200</td>
                            <td>3</td>
                            <td>1</td>
                            <td>2</td>
                            <td>글로벌기업가센터</td>
                            <td></td>
                        </tr>
                        <tr>
                            <td>VEN2009</td>
                            <td>창업기초:스타트업기업가정신의이해와사례</td>
                            <td>200</td>
                            <td>3</td>
                            <td>3</td>
                            <td>0</td>
                            <td>글로벌기업가센터</td>
                            <td></td>
                        </tr>
                        <tr>
                            <td>VEN2001</td>
                            <td>창업기초:창업과기업가정신</td>
                            <td>200</td>
                            <td>3</td>
                            <td>2</td>
                            <td>1</td>
                            <td>글로벌기업가센터</td>
                            <td></td>
                        </tr>
                        <tr>
                            <td>VEN3006</td>
                            <td>창업실습1</td>
                            <td>200</td>
                            <td>3</td>
                            <td>0</td>
                            <td>3</td>
                            <td>글로벌기업가센터</td>
                            <td></td>
                        </tr>
                        <tr>
                            <td>VEN2003</td>
                            <td>창업심화:스타트업 A to Z</td>
                            <td>200</td>
                            <td>3</td>
                            <td>1</td>
                            <td>2</td>
                            <td>글로벌기업가센터</td>
                            <td></td>
                        </tr>
                        <tr>
                            <td>VEN3001</td>
                            <td>창업심화:스타트업법률이슈 <br/>(구, 창업심화:스타트업MBA)</td>
                            <td>300</td>
                            <td>3</td>
                            <td>3</td>
                            <td>0</td>
                            <td>글로벌기업가센터</td>
                            <td></td>
                        </tr>
                        <tr>
                            <td>VEN3009</td>
                            <td>창업심화:스타트업투자유치전략 (구, 창업심화:스타트업투자유치)</td>
                            <td>300</td>
                            <td>3</td>
                            <td>2</td>
                            <td>1</td>
                            <td>글로벌기업가센터</td>
                            <td></td>
                        </tr>
                        <tr>
                            <td>VEN2018</td>
                            <td>창업심화:스타트업마케팅 <br/>(구, 창업심화:창업마케팅)</td>
                            <td>300</td>
                            <td>3</td>
                            <td>1</td>
                            <td>2</td>
                            <td>글로벌기업가센터</td>
                            <td></td>
                        </tr>
                        <tr>
                            <td>VEN3002</td>
                            <td>창업심화:스타트업특허 <br/>(구, 창업심화:특허와창의적사업전략)</td>
                            <td>300</td>
                            <td>3</td>
                            <td>1</td>
                            <td>2</td>
                            <td>글로벌기업가센터</td>
                            <td></td>
                        </tr>
                        <tr>
                            <td>BUS3039</td>
                            <td>벤처창업론</td>
                            <td>300</td>
                            <td>3</td>
                            <td>3</td>
                            <td>3</td>
                            <td>경영학부</td>
                            <td></td>
                        </tr>
                        <tr>
                            <td>VEN4003</td>
                            <td>블록체인과비즈니스모델</td>
                            <td>300</td>
                            <td>3</td>
                            <td>1</td>
                            <td>2</td>
                            <td>글로벌기업가센터</td>
                            <td></td>
                        </tr>
                        <tr>
                            <td>ITE3074</td>
                            <td>소프트웨어기술창업1</td>
                            <td>300</td>
                            <td>3</td>
                            <td>3</td>
                            <td>0</td>
                            <td>컴퓨터소프트웨어학부</td>
                            <td></td>
                        </tr>
                        <tr>
                            <td>VEN3025</td>
                            <td>창업실무:엔엘코드(No-LowCode)를활용한IT서비스기획 <br/>(구, 엔엘코드(No-LowCode)를활용한IT서비스기획)</td>
                            <td>300</td>
                            <td>3</td>
                            <td>3</td>
                            <td>0</td>
                            <td>글로벌기업가센터</td>
                            <td></td>
                        </tr>
                        <tr>
                            <td>BUS3107</td>
                            <td>인공지능과비즈니스</td>
                            <td>300</td>
                            <td>3</td>
                            <td>2</td>
                            <td>1</td>
                            <td>경영학부</td>
                            <td></td>
                        </tr>
                        <tr>
                            <td>VEN3024</td>
                            <td>창업가정신과사회적혁신</td>
                            <td>300</td>
                            <td>3</td>
                            <td>3</td>
                            <td>0</td>
                            <td>글로벌기업가센터</td>
                            <td></td>
                        </tr>
                        <tr>
                            <td>VEN3018</td>
                            <td>창업실무:고객데이터분석및활용기초</td>
                            <td>300</td>
                            <td>3</td>
                            <td>0</td>
                            <td>3</td>
                            <td>글로벌기업가센터</td>
                            <td></td>
                        </tr>
                        <tr>
                            <td>VEN3021</td>
                            <td>창업실무:금융DT와핀테크SW기초</td>
                            <td>300</td>
                            <td>3</td>
                            <td>1</td>
                            <td>2</td>
                            <td>글로벌기업가센터</td>
                            <td></td>
                        </tr>
                        <tr>
                            <td>VEN3020</td>
                            <td>창업실무:모바일게임프로그래밍기초</td>
                            <td>300</td>
                            <td>3</td>
                            <td>0</td>
                            <td>3</td>
                            <td>글로벌기업가센터</td>
                            <td></td>
                        </tr>
                        <tr>
                            <td>VEN3019</td>
                            <td>창업실무:쉽게배우는모바일앱개발</td>
                            <td>300</td>
                            <td>3</td>
                            <td>0</td>
                            <td>3</td>
                            <td>글로벌기업가센터</td>
                            <td></td>
                        </tr>
                        <tr>
                            <td>VEN3017</td>
                            <td>클라우드비즈니스모델</td>
                            <td>300</td>
                            <td>3</td>
                            <td>1</td>
                            <td>2</td>
                            <td>글로벌기업가센터</td>
                            <td></td>
                        </tr>
                        <tr>
                            <td>GEN5026</td>
                            <td>테크노경영학(스타트업종합설계)</td>
                            <td>300</td>
                            <td>3</td>
                            <td>3</td>
                            <td>0</td>
                            <td>공학교육혁신센터</td>
                            <td></td>
                        </tr>
                        <tr>
                            <td>JOB5001</td>
                            <td>단기창업현장실습</td>
                            <td>300</td>
                            <td>3</td>
                            <td>0</td>
                            <td>3</td>
                            <td>글로벌기업가센터</td>
                            <td></td>
                        </tr>
                        <tr>
                            <td>JOB6005</td>
                            <td>창업현장실습(일반선택)</td>
                            <td>300</td>
                            <td>9</td>
                            <td>0</td>
                            <td>9</td>
                            <td>글로벌기업가센터</td>
                            <td>최대 9학점까지 인정</td>
                        </tr>
                        <tr>
                            <td>ITE4083</td>
                            <td>소프트웨어기술창업2</td>
                            <td>400</td>
                            <td>3</td>
                            <td>3</td>
                            <td>0</td>
                            <td>컴퓨터소프트웨어학부</td>
                            <td></td>
                        </tr>
                        <tr>
                            <td>VEN4006</td>
                            <td>창업실무:스타트업경영전략 <br/>(구, 스타트업전략)</td>
                            <td>300</td>
                            <td>3</td>
                            <td>3</td>
                            <td>0</td>
                            <td>글로벌기업가센터</td>
                            <td></td>
                        </tr>
                        <tr>
                            <td>PHE4072</td>
                            <td>스포츠창업론</td>
                            <td>400</td>
                            <td>3</td>
                            <td>3</td>
                            <td>0</td>
                            <td>스포츠산업학과</td>
                            <td></td>
                        </tr>
                        <tr>
                            <td>VEN3014</td>
                            <td>창업실습:스타트랙1</td>
                            <td>400</td>
                            <td>3</td>
                            <td>1</td>
                            <td>2</td>
                            <td>글로벌기업가센터</td>
                            <td>247스타트업돔 입사생 대상 강좌</td>
                        </tr>
                        <tr>
                            <td>VEN2002</td>
                            <td>창업실습:실전창업워크숍</td>
                            <td>400</td>
                            <td>3</td>
                            <td>0</td>
                            <td>3</td>
                            <td>글로벌기업가센터</td>
                            <td></td>
                        </tr>
                        <tr>
                            <td>VEN3005</td>
                            <td>창업실습:캠퍼스CEO</td>
                            <td>400</td>
                            <td>3</td>
                            <td>0</td>
                            <td>3</td>
                            <td>글로벌기업가센터</td>
                            <td></td>
                        </tr>
                        <tr>
                            <td>VEN4001</td>
                            <td>창업실습:캡스톤디자인</td>
                            <td>400</td>
                            <td>3</td>
                            <td>0</td>
                            <td>3</td>
                            <td>글로벌기업가센터</td>
                            <td></td>
                        </tr>
                        <tr>
                            <td>VEN3007</td>
                            <td>창업실습2</td>
                            <td>400</td>
                            <td>3</td>
                            <td>0</td>
                            <td>3</td>
                            <td>글로벌기업가센터</td>
                            <td></td>
                        </tr>
                        <tr>
                            <td>TOU3083</td>
                            <td>디지털트랜스포메이션과관광혁신창업</td>
                            <td>400</td>
                            <td>3</td>
                            <td>3</td>
                            <td>0</td>
                            <td>관광학부</td>
                            <td></td>
                        </tr>
                        <tr>
                            <td>ITE4012</td>
                            <td>신제품개발</td>
                            <td>400</td>
                            <td>3</td>
                            <td>3</td>
                            <td>0</td>
                            <td>산업융합학부 경영공학전공</td>
                            <td></td>
                        </tr>
                        <tr>
                            <td>APS4022</td>
                            <td>비즈니스모델디자인</td>
                            <td>400</td>
                            <td>3</td>
                            <td>3</td>
                            <td>0</td>
                            <td>산업융합학부 경영공학전공</td>
                            <td></td>
                        </tr>
                    </tbody>
                </table>
            </div>
        </>
    );
};

export default Edu2024;